monedas = [
    "S/ - Sol peruano",
    "$ - Dólar estadounidense",
    "€ - Euro",
    "¥ - Yen japonés",
    "£ - Libra esterlina",
    "$ - Peso mexicano",
    "$ - Peso argentino",
    "R$ - Real brasileño",
    "$ - Peso chileno",
    "$ - Peso colombiano",
    "₿ - Balboa panameño",
    "₡ - Colón costarricense",
    "₲ - Guaraní paraguayo",
    "$U - Peso uruguayo",
    "Bs - Boliviano",
    "₫ - Dong vietnamita",
    "₹ - Rupia india",
    "₩ - Won surcoreano",
    "₽ - Rublo ruso",
    "₺ - Lira turca",
    "₦ - Naira nigeriana",
    "R - Rand sudafricano",
    "₪ - Nuevo séquel israelí",
    "₱ - Peso filipino",
    "฿ - Baht tailandés",
    "₴ - Grivna ucraniana",
    "Kč - Corona checa",
    "zł - Zloty polaco",
    "kr - Corona sueca",
    "kr - Corona noruega",
    "kr - Corona danesa"
]
